/*
 * File: app/view/appmain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.appmain', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.appmain',

    requires: [
        'pagaf.view.appmainViewModel',
        'pagaf.view.home.topmenu',
        'pagaf.view.home.bottommenu',
        'pagaf.view.InSeason.N.Selection',
        'pagaf.view.InSeason.N.Management',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'appmain'
    },
    defaultListenerScope: true,
    scrollable: 'vertical',
    width: '1440px',
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            scrollable: 'vertical',
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '200px',
                    html: '<div id="header"><div class="height100p center container_8"><div class="grid_3"><a href="https://pagaf.nltmso.com/index.html"><img src="./resources/images/logos/FinalPAGAF2022_01.svg" class="logo"></a></div><div class="grid_5"><div class="navLink green"><a href="https://pagaf.nltmso.com/index.html#Technology" class="green">Technology</a></div><div class="navLink green"><a href="https://pagaf.nltmso.com/index.html#Story" class="green">Our Story</a></div><div class="navLink green"><a href="https://pagaf.nltmso.com/index.html#Blog" class="green">Blog</a></div><div class="navLink green"><a href="https://pagaf.nltmso.com/index.html#Support" class="green">Support</a></div><div id="topright"><button id="logout" class="organization">Log Out</button> <button id="organization" class="organization"></button></div></div></div> </div>',
                    maxHeight: 200,
                    minHeight: 200,
                    width: '100%'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    id: 'mainCardPanel',
                    layout: 'card',
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            id: 'home',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'home.topmenu',
                                    hidden: true
                                },
                                {
                                    xtype: 'home.bottommenu'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'Tools',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'Report',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'Data',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'inSeasonNMgmt',
                            layout: 'accordion',
                            title: 'In Season N Management',
                            items: [
                                {
                                    xtype: 'inseason.n.selection',
                                    title: '1. Field Selection',
                                    titleAlign: 'center'
                                },
                                {
                                    xtype: 'inseason.n.management',
                                    disabled: true,
                                    hidden: true,
                                    title: '2. Management',
                                    titleAlign: 'center'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            height: 250,
                            id: 'inSeasonMainTab',
                            width: 400,
                            title: 'In Season N Management',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'inSeasonTab1',
                                    title: '1. Managment',
                                    layout: {
                                        type: 'vbox',
                                        align: 'center'
                                    },
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab2',
                                    title: '2. Credits',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick1'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab3',
                                    title: '3. Economics',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick11'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab4',
                                    title: '4. Review',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick111'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab5',
                                    title: '5. Finish',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick1111'
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '200px',
                    html: '<div id="footer"> <div class="center container_8"> <div class="grid_3 leftPadding"> <img src="./resources/images/logos/FinalPAGAF2022_01.svg" class="footerPagaf"> <h5 class="green clearBoth footerTalk ">Talk to us at:</h5> <p class="noMargins"><a href="mailto:info@nltpagaf.ai" class="gray clearBoth">info@nltpagaf.ai</a></p> <a href="https://github.com/NLTGit/"><img src="./resources/images/logos/github.png" class="socialMedia"></a> <a href="https://www.linkedin.com/in/newlighttechnologies"><img src="./resources/images/logos/linkedin.png" class="socialMediaNext"></a> <a href="https://www.facebook.com/NewLightTechnologies/"><img src="./resources/images/logos/facebook.png" class="socialMediaNext"></a> <a href="https://twitter.com/newlighttech"><img src="./resources/images/logos/twitter.png" class="socialMediaNext"></a> </div> <div class="grid_1 footerMenu"> <h4 class="green">Product</h4> <a href="#" class="gray footerSubMenu">Team</a> <a href="#" onclick="show(\'technology\');" class="gray footerSubMenu">Technology</a> <a href="#" class="gray footerSubMenu">For Investors</a> </div> <div class="grid_1 footerMenu"> <h4 class="green">About Us</h4> <a href="#" class="gray footerSubMenu">NLT</a> <a href="#" onclick="show(\'blog\');" class="gray footerSubMenu">Blog</a> </div> <div class="grid_1 footerMenu"> <h4 class="green">Support</h4> <a href="#" class="gray footerSubMenu">Product Improvements</a> <a href="#" class="gray footerSubMenu">Updates</a> </div> <div class="grid_8 space100"></div> <div class="grid_8"> <span class="poweredByFooter gray noMargins">Powered By</span> <a href="https://nltgis.com&quot;"><img src="./resources/images/logos/nltlogo.png" class="poweredByFooterNLT"></a> </div> </div> </div>',
                    maxHeight: 200,
                    minHeight: 200,
                    width: '100%'
                }
            ]
        }
    ],

    onTabClick: function(button, e, eOpts) {

    },

    onTabClick1: function(button, e, eOpts) {

    },

    onTabClick11: function(button, e, eOpts) {

    },

    onTabClick111: function(button, e, eOpts) {

    },

    onTabClick1111: function(button, e, eOpts) {

    }

});