/*
 * File: app/view/appmain.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.appmain', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.appmain',

    requires: [
        'pagaf.view.appmainViewModel',
        'pagaf.view.home.topmenu',
        'pagaf.view.home.bottommenu',
        'pagaf.view.InSeason.N.Selection',
        'pagaf.view.InSeason.N.Management',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'appmain'
    },
    defaultListenerScope: true,
    scrollable: true,
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            scrollable: true,
            layout: 'fit',
            items: [
                {
                    xtype: 'container',
                    height: '220px',
                    html: '<div id="header"> <span id="logo">   <span class="precision">Precision</span>   <span class="ag">AG</span>   <span class="for-farmers">for American Farmers</span>   <sub class="demo">Demo <a href="https://github.com/NLTGit/pagaf/wiki">About</a></sub> </span> <div id="topright"> <button id="logout" class="organization">Log Out</button> <button id="organization" class="organization"></button> </div></div>',
                    maxHeight: 220,
                    minHeight: 220,
                    width: '100%'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    id: 'mainCardPanel',
                    layout: 'card',
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            id: 'home',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'home.topmenu'
                                },
                                {
                                    xtype: 'home.bottommenu'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'Tools',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'Report',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'Data',
                            layout: 'accordion',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            id: 'inSeasonNMgmt',
                            layout: 'accordion',
                            title: 'In Season N Management',
                            items: [
                                {
                                    xtype: 'inseason.n.selection',
                                    title: '1. Field Selection',
                                    titleAlign: 'center'
                                },
                                {
                                    xtype: 'inseason.n.management',
                                    disabled: true,
                                    hidden: true,
                                    title: '2. Management',
                                    titleAlign: 'center'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            height: 250,
                            id: 'inSeasonMainTab',
                            width: 400,
                            title: 'In Season N Management',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'inSeasonTab1',
                                    title: '1. Managment',
                                    layout: {
                                        type: 'vbox',
                                        align: 'center'
                                    },
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab2',
                                    title: '2. Credits',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick1'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab3',
                                    title: '3. Economics',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick11'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab4',
                                    title: '4. Review',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick111'
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    id: 'inSeasonTab5',
                                    title: '5. Finish',
                                    tabConfig: {
                                        xtype: 'tab',
                                        listeners: {
                                            click: 'onTabClick1111'
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '200px',
                    html: '<div id="footer"><div id="footerimg"></div><div id="social" /></div><div id="tag">PAGAF: Precision Agriculture for all American Farmers. Copyright (C) 2020, New Light Technologies. <a href="https://github.com/NLTGit/pagaf/wiki#legal">Legal</a></div></div>',
                    maxHeight: 200,
                    minHeight: 200,
                    width: '100%'
                }
            ]
        }
    ],

    onTabClick: function(button, e, eOpts) {

    },

    onTabClick1: function(button, e, eOpts) {

    },

    onTabClick11: function(button, e, eOpts) {

    },

    onTabClick111: function(button, e, eOpts) {

    },

    onTabClick1111: function(button, e, eOpts) {

    }

});