/*
 * File: app/view/pagafAppWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.pagafAppWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.pagafappwindow',

    requires: [
        'pagaf.view.pagafAppWindowViewModel'
    ],

    viewModel: {
        type: 'pagafappwindow'
    },
    flex: 1,
    height: '100%',
    id: 'pagafwindow',
    width: '100%',
    closable: false,
    defaultListenerScope: true,

    listeners: {
        afterrender: 'onPagafAfterRender'
    },

    onPagafAfterRender: function(component, eOpts) {
        component.setHtml('<iframe src="home2.html" width="100%" height="100%" />');
    }

});