/*
 * File: app/view/InSeason/N/Management.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.InSeason.N.Management', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.inseason.n.management',

    requires: [
        'pagaf.view.InSeason.N.ManagementViewModel',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'inseason.n.management'
    },
    id: 'isnm_management',
    margin: 'auto 0',
    width: '80%',
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'datefield',
            cls: 'mediumTxt',
            height: 50,
            width: 600,
            fieldLabel: 'When did you plant?',
            labelWidth: 400,
            matchFieldWidth: false
        },
        {
            xtype: 'numberfield',
            height: 50,
            width: 600,
            fieldLabel: 'How much N have you already applied?',
            labelWidth: 400
        },
        {
            xtype: 'button',
            scale: 'large',
            text: 'Next',
            listeners: {
                click: 'onButtonClick'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var t = Ext.getCmp('isnm_credits');
        t.expand();
        t.setDisabled(false);
        t.setVisible(true);
        var t = Ext.getCmp('isnm_management');
        t.setDisabled(true);
        t.setVisible(false);
    }

});