/*
 * File: app/view/InSeason/N/Selection.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.InSeason.N.Selection', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.inseason.n.selection',

    requires: [
        'pagaf.view.InSeason.N.ManagementViewModel5',
        'pagaf.view.pagafAppPanel',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'inseason.n.selection'
    },
    id: 'isnm_selection',
    margin: 'auto 0',
    width: '80%',
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'pagafapppanel',
            flex: 1
        },
        {
            xtype: 'button',
            scale: 'large',
            text: 'Next',
            listeners: {
                click: 'onButtonClick'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var t = Ext.getCmp('isnm_selection');
        t.setDisabled(true);
        t.setVisible(false);

        if(t.getTitle().search('4.') > -1){
            t.setTitle('1. Select field');
            t = Ext.getCmp('isnm_review');
        } else {
            t = Ext.getCmp('isnm_management');
        }
        t.expand();
        t.setDisabled(false);
        t.setVisible(true);
    }

});