/*
 * File: app/view/home/bottommenu.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.home.bottommenu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.home.bottommenu',

    requires: [
        'pagaf.view.home.topmenuViewModel1',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'home.bottommenu'
    },
    flex: 1,
    id: 'homeBtmMenu',
    width: '',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            cls: 'XLText',
            height: 150,
            html: '<center><h1>Management Tools</h2></center>'
        },
        {
            xtype: 'container',
            flex: 1,
            height: 200,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    margins: '20',
                    cls: 'largeTxt',
                    componentCls: '',
                    height: 150,
                    margin: 20,
                    padding: '',
                    width: 150,
                    text: 'In-Season N Mgmt',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    margins: '20',
                    cls: 'largeTxt',
                    height: 150,
                    margin: 20,
                    padding: '',
                    width: 150,
                    text: 'Seeding Rate Rx'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            height: 200,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    margins: '20',
                    cls: 'largeTxt',
                    height: 150,
                    margin: 20,
                    width: 150,
                    text: 'Planting Date <br /> Decision Making'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    margins: '20',
                    cls: 'largeTxt',
                    height: 150,
                    margin: 20,
                    padding: '',
                    width: 150,
                    text: 'Fungicide Wheat'
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp("mainCardPanel").getLayout().setActiveItem('inSeasonNMgmt');
    }

});