/*
 * File: app/view/home/topmenu.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pagaf.view.home.topmenu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.home.topmenu',

    requires: [
        'pagaf.view.home.topmenuViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'home.topmenu'
    },
    height: 100,
    id: 'homeTopMenu',
    width: '',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'button',
            flex: 1,
            margin: 20,
            scale: 'medium',
            text: 'Home'
        },
        {
            xtype: 'button',
            flex: 1,
            margin: 20,
            scale: 'medium',
            text: 'Tools'
        },
        {
            xtype: 'button',
            flex: 1,
            margin: 20,
            scale: 'medium',
            text: 'Report'
        },
        {
            xtype: 'button',
            flex: 1,
            margin: 20,
            scale: 'medium',
            text: 'Data'
        }
    ]

});